### ISSUE TITLE
ColumnDefault annotation doesn't work because JDBC driver accepts NULL values as valid 

### ISSUE THREAD

**Issue by ChengyuanZhao** [GoogleCloudPlatform/google-cloud-spanner-hibernate#75] opened 2019-04-02 18:48 UTC
usually NULL cannot be stored in a database, so the `@ColumnDefault` annotation value kicks in.

However Spanner can store NULL directly so the JDBC driver never falls back to the default value.

**Comment by meltsufin** [comment] 2019-04-02 19:26
usually `NULL` cannot be store in a database??

**Comment by ChengyuanZhao** [comment] 2019-04-02 19:36
@meltsufin  The binding of values happens in the `PreparedStatement` implementation of each driver and for example in Postgresql and Mysql there is special treatment for null values as the parameters of the insert DML that were null are remembered so the default values can be used presumably. 

In the Spanner JDBC the null value is just bound to the DML statement like any other value.

**Comment by meltsufin** [comment] 2019-04-02 19:58
I see, it has to do with column defaults that are supported in some dbs.

**Comment by meltsufin** [comment] 2019-11-11 20:00
@olavloite Can this be fixed in the JDBC driver?

**Comment by olavloite** [comment] 2019-11-13 08:27
@meltsufin It's not clear to me exactly what the issue is here:
* The `PreparedStatement` interface in JDBC has two `setNull(...)` methods for setting parameters to `NULL`. These are both supported by the Spanner JDBC driver and should be called when you want to send a `NULL` value to the database.
* The `@ColumnDefault` is AFAIK only used by Hiberante for DDL generation, and not when generating values for the column during data insertion (See https://docs.jboss.org/hibernate/orm/5.4/javadocs/org/hibernate/annotations/ColumnDefault.html). Cloud Spanner (the backend) does not support DEFAULT values for columns, so this annotation cannot be used with Spanner.

Or am I missing something here?

**Comment by meltsufin** [comment] 2019-11-13 14:55
Thanks @olavloite! The documentation clearly states that `@ColumnDefault`
> Identifies the DEFAULT value to apply to the associated column via DDL.

Since Cloud Spanner doesn't support column defaults, there's nothing we can do about it and should just document this as a missing feature.

@ChengyuanZhao WDYT?

**Comment by ChengyuanZhao** [comment] 2019-11-13 15:06
Got it, that makes sense. Sounds good to me.

**Comment by meltsufin** [comment] 2019-11-13 15:23
We actually already document it, but I think the wording is wrong.

> The dialect does not currently set default values based on the @ColumnDefault annotation, because NULL values aren’t specially handled and are stored just like other values by Cloud Spanner and its driver.

Should be:

> The dialect does not currently set default values based on the @ColumnDefault annotation, because Cloud Spanner does not support column defaults in the DDL.

**Comment by meltsufin** [comment] 2019-11-15 20:34
Will be handled in #164 as a doc update.

**Closed by meltsufin** 2019-11-15 20:34 UTC
Labels: P2, unsupported feature

**Comment by Anakinud** [comment] 2024-10-06 19:03
Hello, could you update code and/or specification because Spanner added support for column default values? I can't see anything about it in current spec

**Comment by olavloite** [comment] 2024-10-21 14:34
@Anakinud Yes, `@ColumnDefault` is now supported. It however requires a couple of extra steps to actually work (this has to do with Hibernate, and not specifically Spanner):
1. You need to specify `@DynamicInsert` for the entity to ensure that Hibernate only generates an insert column expression for the columns that actually have a value.
2. Hibernate needs to think that the column is nullable (that is; you can manually change the column in the database later to be NOT NULL, but you can't add `@Column(nullable = false)` to your code).

Note also that adding `@DynamicInsert` stops Hibernate from batching multiple inserts of the same entity into one request.

See https://github.com/GoogleCloudPlatform/google-cloud-spanner-hibernate/pull/1365 for the sample that is being added.
